// dsh-app-launcher — profile bundle plugin
//
// Turns the DSH Web GUI into a desktop app:
//   1. after the web server is listening (webServer service appears), open the
//      GUI in a dedicated browser app window (own --user-data-dir, so your
//      normal browser profile is never touched);
//   2. when that window is closed, request a graceful process shutdown through
//      the launcher-provided `appExit` service — the npx/cmd wrapper exits on
//      its own, so no external watcher or taskkill is needed;
//   3. optional (Windows): `createShortcut` generates a hidden-start VBS, an
//      .ico, and a Desktop .lnk pointing at them, so a fresh environment gets
//      a one-click launcher automatically;
//   4. optional: `disableSpellcheck` kills red squiggles in the app window —
//      a probe script injected into the served page sets spellcheck=false on
//      every editable element (re-applied via MutationObserver), and the
//      dedicated profile's Preferences get spellcheck.enable / browser.
//      enable_spellchecking set to false as a best-effort browser-level off;
//   5. optional: `rememberWindow` remembers the app-window size and position
//      across restarts — a tiny probe script injected into the served index
//      page reports screenX/screenY/outerWidth/outerHeight to a local route,
//      which persists them; the next launch restores them via
//      --window-size/--window-position.
//
// Config (patch row):
//   enabled:          true   (default)  mount the behavior at all
//   openOnStart:      true   (default)  open the app window on startup
//   exitOnClose:      true   (default)  shut DSH down when the window closes
//   browser:          auto   (default)  'auto' | 'chrome' | 'edge'
//   profileDir:       <dsh-home>/app-window/<browser>   dedicated browser profile
//   disableSpellcheck: true  (default)  disable red squiggles in the app window
//                                     (page-level spellcheck=false + profile prefs)
//   rememberWindow:   true   (default)  remember window size/position across restarts
//   windowStateFile:  <dsh-home>/app-window/window-state.json  geometry state file
//   createShortcut:   true   (default)  create a Desktop launcher shortcut (Windows);
//                                     disable explicitly with false
//   shortcutName:     'DSH'              name of the shortcut (without .lnk)
//   launcherDir:      <dsh-home>/launcher               where VBS/ICO are written
//   desktopDir:       (auto)            target folder for the .lnk (defaults to the real Desktop)

import { spawn } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { ICON_BASE64 } from "./icon.js";

export const name = "app-launcher";

/** Activate only after the web server has bound its socket. */
export const inject = ["webServer"];

const BROWSER_CANDIDATES = {
    win32: [
        { name: "chrome", exe: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" },
        { name: "chrome", exe: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" },
        { name: "edge", exe: "C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe" },
        { name: "edge", exe: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe" }
    ],
    linux: [
        { name: "chrome", exe: "/usr/bin/google-chrome" },
        { name: "chrome", exe: "/usr/bin/google-chrome-stable" },
        { name: "chromium", exe: "/usr/bin/chromium" },
        { name: "edge", exe: "/usr/bin/microsoft-edge" }
    ],
    darwin: [
        { name: "chrome", exe: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" },
        { name: "edge", exe: "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge" }
    ]
};

function dshHome() {
    return process.env.DSH_HOME || join(homedir(), ".dsh");
}

/** Embed a value in the generated PowerShell script as a single-quoted PS string literal. */
function psQuote(value) {
    return "'" + String(value).replace(/'/g, "''") + "'";
}

/**
 * Create a Desktop shortcut (Windows only): a hidden-start VBS launcher plus
 * an .ico, then a .lnk on the Desktop pointing at wscript.exe + the VBS.
 * Never clobbers existing files: anything already present is left alone.
 * Runs asynchronously via a hidden PowerShell process.
 */
function createDesktopShortcut(ctx, cfg) {
    if (process.platform !== "win32") {
        ctx.logger.info("[app-launcher] createShortcut is Windows-only; skipping");
        return;
    }
    const launcherDir = cfg.launcherDir || join(dshHome(), "launcher");
    const shortcutName = cfg.shortcutName || "DSH";
    const desktopOverride = cfg.desktopDir || "";

    const vbsContent = [
        "' DSH hidden launcher — auto-generated by dsh-app-launcher",
        "' Double-click the Desktop shortcut, or run this file with wscript.",
        "Set shell = CreateObject(\"WScript.Shell\")",
        "shell.Run \"cmd /c npx --yes @deepseek-ai/dsh web\", 0, False"
    ].join("\r\n");

    const script = [
        "$ErrorActionPreference = 'Stop'",
        `$launcherDir = ${psQuote(launcherDir)}`,
        `$shortcutName = ${psQuote(shortcutName)}`,
        `$desktopOverride = ${psQuote(desktopOverride)}`,
        "New-Item -ItemType Directory -Force -Path $launcherDir | Out-Null",
        "$vbsPath = Join-Path $launcherDir 'start-dsh.vbs'",
        "$icoPath = Join-Path $launcherDir 'dsh.ico'",
        "if (-not (Test-Path $vbsPath)) {",
        "  $vbsContent = @'",
        vbsContent,
        "'@",
        "  [System.IO.File]::WriteAllText($vbsPath, $vbsContent, (New-Object System.Text.UTF8Encoding($false)))",
        "}",
        "if (-not (Test-Path $icoPath)) {",
        "  [System.IO.File]::WriteAllBytes($icoPath, [Convert]::FromBase64String('" + ICON_BASE64 + "'))",
        "}",
        "$desktop = if ($desktopOverride) { $desktopOverride } else { [Environment]::GetFolderPath('Desktop') }",
        "if (-not $desktop) { throw 'cannot resolve Desktop path' }",
        "New-Item -ItemType Directory -Force -Path $desktop | Out-Null",
        "$lnk = Join-Path $desktop ($shortcutName + '.lnk')",
        "if (Test-Path $lnk) { Write-Output ('SKIP (exists): ' + $lnk); exit 0 }",
        "$ws = New-Object -ComObject WScript.Shell",
        "$sc = $ws.CreateShortcut($lnk)",
        "$sc.TargetPath = Join-Path $env:windir 'System32\\wscript.exe'",
        "$sc.Arguments = '\"' + $vbsPath + '\"'",
        "$sc.WorkingDirectory = $env:USERPROFILE",
        "$sc.IconLocation = $icoPath + ',0'",
        "$sc.Description = 'Start DeepSeek Harness (DSH) Web GUI'",
        "$sc.Save()",
        "Write-Output ('CREATED: ' + $lnk)"
    ].join("\r\n");

    // The generated script embeds a ~25 KB icon, which would overflow the Windows
    // command line — write it to a temp .ps1 (UTF-8 with BOM so both PowerShell
    // 5.1 and 7 decode non-ASCII paths correctly) and run it with -File.
    let ps1Path;
    try {
        ps1Path = join(tmpdir(), `dsh-create-shortcut-${process.pid}.ps1`);
        writeFileSync(ps1Path, "\uFEFF" + script, "utf8");
    } catch (error) {
        const msg = `[app-launcher] shortcut creation failed to write script: ${error.message}`;
        ctx.logger.warn(msg);
        console.log(msg);
        return;
    }
    let child;
    try {
        child = spawn("powershell.exe", [
            "-NoProfile", "-WindowStyle", "Hidden", "-ExecutionPolicy", "Bypass",
            "-File", ps1Path
        ], {
            stdio: ["ignore", "pipe", "pipe"],
            windowsHide: true
        });
    } catch (error) {
        const msg = `[app-launcher] shortcut creation failed to start: ${error.message}`;
        ctx.logger.warn(msg);
        console.log(msg);
        return;
    }
    let out = "";
    child.stdout.on("data", (d) => { out += String(d); });
    child.stderr.on("data", (d) => { out += String(d); });
    child.on("error", (error) => {
        const msg = `[app-launcher] shortcut creation failed: ${error.message}`;
        ctx.logger.warn(msg);
        console.log(msg);
    });
    child.on("exit", (code) => {
        const msg = `[app-launcher] desktop shortcut: ${out.trim() || `exit ${code}`}`;
        ctx.logger.info(msg);
        console.log(msg);
    });
}

// ---------------------------------------------------------------------------
// Window geometry memory (size + position across restarts)
// ---------------------------------------------------------------------------

/** JSON file holding the last app-window geometry (browser-agnostic). */
export function windowStatePath(cfg) {
    return cfg.windowStateFile || join(dshHome(), "app-window", "window-state.json");
}

/**
 * Read and validate saved geometry. Returns {x, y, w, h} (screenX/screenY and
 * outerWidth/outerHeight, DIPs) or null when absent or implausible. The
 * -32000 minimized sentinel and other degenerate values are rejected here.
 */
export function readWindowState(path) {
    let raw;
    try {
        raw = readFileSync(path, "utf8");
    } catch {
        return null;
    }
    try {
        const s = JSON.parse(raw);
        const x = Number(s.x), y = Number(s.y), w = Number(s.w), h = Number(s.h);
        const ok = Number.isFinite(x) && Number.isFinite(y)
            && Number.isFinite(w) && Number.isFinite(h)
            && w >= 200 && h >= 200
            && x > -20000 && x < 20000 && y > -20000 && y < 20000;
        return ok ? { x, y, w, h } : null;
    } catch {
        return null;
    }
}

/** Atomically persist geometry (temp file + rename). Throws on failure. */
export function writeWindowState(path, state) {
    mkdirSync(dirname(path), { recursive: true });
    const tmp = path + ".tmp";
    writeFileSync(tmp, JSON.stringify(state));
    renameSync(tmp, path);
}

/** Command-line flags restoring a saved geometry (outer size + position). */
export function composeRestoreArgs(saved) {
    if (!saved) return [];
    return [
        `--window-size=${saved.w},${saved.h}`,
        `--window-position=${saved.x},${saved.y}`
    ];
}

// ---------------------------------------------------------------------------
// Spellcheck: no red squiggles in the app window
// ---------------------------------------------------------------------------

/**
 * Best-effort browser-level off: merge the spellcheck master prefs into the
 * profile's Preferences file before Chrome starts. Chrome 150 registers
 * `browser.enable_spellchecking`; older versions used `spellcheck.enable`.
 * Writing both is harmless — unknown keys are simply preserved. The profile
 * prefs live at <user-data-dir>/Default/Preferences (Chrome ignores a bare
 * Preferences file at the user-data-dir root). Returns true when the file was
 * changed, false when both were already off. Throws when Preferences exists
 * but cannot be parsed (never clobbers an unreadable profile).
 */
export function disableSpellcheck(profileDir) {
    const prefsDir = join(profileDir, "Default");
    mkdirSync(prefsDir, { recursive: true });
    const prefsPath = join(prefsDir, "Preferences");
    let prefs = {};
    if (existsSync(prefsPath)) {
        const raw = readFileSync(prefsPath, "utf8");
        try {
            prefs = JSON.parse(raw);
        } catch (error) {
            throw new Error(`cannot parse ${prefsPath}: ${error.message}`);
        }
    }
    const already = (prefs.spellcheck && prefs.spellcheck.enable === false)
        && (prefs.browser && prefs.browser.enable_spellchecking === false);
    if (already) return false;
    prefs.spellcheck = Object.assign({}, prefs.spellcheck, { enable: false });
    prefs.browser = Object.assign({}, prefs.browser, { enable_spellchecking: false });
    writeFileSync(prefsPath, JSON.stringify(prefs));
    return true;
}

/**
 * The tiny client script injected into the GUI page: sets spellcheck=false on
 * every input/textarea/contenteditable, re-applying it as the app re-renders
 * (MutationObserver). This is the deterministic, version-proof fix — it does
 * not depend on which pref the installed Chrome happens to use.
 */
export function spellcheckProbeScript() {
    return [
        "<script>",
        "(function(){",
        "if(location.search.indexOf('__dsh_app=1')===-1)return;",
        "function off(){",
        "var els=document.querySelectorAll('input,textarea,[contenteditable]');",
        "for(var i=0;i<els.length;i++){els[i].spellcheck=false;}",
        "}",
        "off();",
        "if(window.MutationObserver){new MutationObserver(off).observe(document,{childList:true,subtree:true});}",
        "})();",
        "</script>"
    ].join("");
}

/** tapIndex transform: inject the spellcheck killer once, right before </head>. */
export function spellcheckTap(html) {
    const script = spellcheckProbeScript();
    if (html.includes(script)) return html;
    const marker = "</head>";
    const at = html.lastIndexOf(marker);
    if (at === -1) return html + script;
    return html.slice(0, at) + script + html.slice(at);
}

// ---------------------------------------------------------------------------
// In-page geometry probe (injected into the served GUI page)
// ---------------------------------------------------------------------------

/**
 * The tiny client script injected into the GUI index page. It only reports
 * from the app window (URL carries ?__dsh_app=1) and posts the window's
 * screenX/screenY/outerWidth/outerHeight to the local route. keepalive makes
 * the final report survive window close.
 */
export function geometryProbeScript() {
    return [
        "<script>",
        "(function(){",
        "function save(){",
        "var x=window.screenX,y=window.screenY,w=window.outerWidth,h=window.outerHeight;",
        "if(!(w>100&&h>100))return;",
        "if(x<-20000||y<-20000)return;",
        "if(location.search.indexOf('__dsh_app=1')===-1)return;",
        "try{",
        "fetch('/__dsh-window-state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({x:x,y:y,w:w,h:h}),keepalive:true});",
        "}catch(e){}",
        "}",
        "window.addEventListener('resize',save);",
        "window.addEventListener('move',save);",
        "window.addEventListener('beforeunload',save);",
        "window.setInterval(save,5000);",
        "})();",
        "</script>"
    ].join("");
}

/** tapIndex transform: inject the probe script once, right before </head>. */
export function geometryTap(html) {
    const script = geometryProbeScript();
    if (html.includes(script)) return html;
    const marker = "</head>";
    const at = html.lastIndexOf(marker);
    if (at === -1) return html + script;
    return html.slice(0, at) + script + html.slice(at);
}

/** webServer route receiving the probe's reports and persisting them. */
export function registerWindowStateRoute(ctx, statePath) {
    return ctx.webServer.register({
        kind: "exact",
        path: "/__dsh-window-state",
        handler: (req, res) => {
            if (req.method !== "POST") {
                res.writeHead(405).end();
                return;
            }
            let body = "";
            req.on("data", (chunk) => {
                if (body.length < 8192) body += String(chunk);
            });
            req.on("end", () => {
                try {
                    const s = JSON.parse(body);
                    const x = Number(s.x), y = Number(s.y), w = Number(s.w), h = Number(s.h);
                    const ok = Number.isFinite(x) && Number.isFinite(y)
                        && Number.isFinite(w) && Number.isFinite(h)
                        && w >= 200 && h >= 200
                        && x > -20000 && x < 20000 && y > -20000 && y < 20000;
                    if (ok) writeWindowState(statePath, { x, y, w, h });
                    res.writeHead(204).end();
                } catch (error) {
                    ctx.logger.warn(`[app-launcher] bad window-state report: ${error.message}`);
                    res.writeHead(400).end();
                }
            });
        }
    });
}

// ---------------------------------------------------------------------------

export function apply(ctx, config = {}) {
    const cfg = config || {};
    if (cfg.enabled === false) return;

    const openOnStart = cfg.openOnStart !== false;
    const exitOnClose = cfg.exitOnClose !== false;
    const rememberWindow = cfg.rememberWindow !== false;
    const wantBrowser = cfg.browser && cfg.browser !== "auto" ? cfg.browser : undefined;

    const port = ctx.webServer?.port;
    if (typeof port !== "number") {
        ctx.logger.warn("[app-launcher] webServer.port unavailable; nothing to do");
        return;
    }
    const url = `http://127.0.0.1:${port}`;

    if (cfg.createShortcut !== false) {
        createDesktopShortcut(ctx, cfg);
    }

    // Window geometry memory: probe (in page) -> route -> state file.
    const statePath = windowStatePath(cfg);
    let probeWired = false;
    if (rememberWindow) {
        try {
            if (typeof ctx.webServer.tapIndex === "function" && typeof ctx.webServer.register === "function") {
                const disposeTap = ctx.webServer.tapIndex(geometryTap);
                const disposeRoute = registerWindowStateRoute(ctx, statePath);
                ctx.effect(() => () => {
                    disposeTap();
                    disposeRoute();
                });
                probeWired = true;
                ctx.logger.info(`[app-launcher] window size/position will be remembered (${statePath})`);
            } else {
                ctx.logger.warn("[app-launcher] rememberWindow: this DSH build has no webServer.tapIndex; window geometry will not be tracked");
            }
        } catch (error) {
            ctx.logger.warn(`[app-launcher] rememberWindow: ${error.message}`);
        }
    }

    // Spellcheck: inject the page-level killer (works in every Chrome/Edge
    // version regardless of which pref it uses) and later disable the
    // profile-level prefs as a best effort.
    if (cfg.disableSpellcheck !== false) {
        try {
            if (typeof ctx.webServer.tapIndex === "function") {
                const disposeTap = ctx.webServer.tapIndex(spellcheckTap);
                ctx.effect(() => () => { disposeTap(); });
                ctx.logger.info("[app-launcher] spellcheck will be disabled in the app window");
            } else {
                ctx.logger.warn("[app-launcher] disableSpellcheck: this DSH build has no webServer.tapIndex; falling back to profile prefs only");
            }
        } catch (error) {
            ctx.logger.warn(`[app-launcher] disableSpellcheck: ${error.message}`);
        }
    }

    if (!openOnStart) {
        ctx.logger.info(`[app-launcher] openOnStart disabled; GUI at ${url}`);
        return;
    }

    const candidates = BROWSER_CANDIDATES[process.platform] ?? [];
    const preferred = wantBrowser ? candidates.filter((c) => c.name === wantBrowser) : [];
    const browser = (preferred.find((c) => existsSync(c.exe)))
        ?? candidates.find((c) => existsSync(c.exe));

    if (!browser) {
        ctx.logger.warn(`[app-launcher] no supported browser found (${candidates.map((c) => c.name).join(", ")}); open ${url} manually`);
        return;
    }

    const profileDir = cfg.profileDir || join(dshHome(), "app-window", browser.name);
    try {
        mkdirSync(profileDir, { recursive: true });
    } catch (error) {
        ctx.logger.warn(`[app-launcher] cannot create profile dir ${profileDir}: ${error.message}`);
        return;
    }

    // Spellcheck: force the dedicated profile's spellcheck prefs off too.
    if (cfg.disableSpellcheck !== false) {
        try {
            if (disableSpellcheck(profileDir)) {
                ctx.logger.info("[app-launcher] spellcheck prefs disabled in the app-window profile");
            }
        } catch (error) {
            ctx.logger.warn(`[app-launcher] cannot disable spellcheck prefs: ${error.message}`);
        }
    }

    // The probe only reports from the app window (its URL carries the marker).
    const appUrl = probeWired ? `${url}?__dsh_app=1` : url;

    const args = [
        `--user-data-dir=${profileDir}`,
        `--app=${appUrl}`,
        "--no-first-run",
        "--no-default-browser-check"
    ];
    if (rememberWindow) {
        args.push(...composeRestoreArgs(readWindowState(statePath)));
    }

    // NOTE: no windowsHide here. windowsHide:true sets STARTUPINFO.wShowWindow=
    // SW_HIDE, which propagates to Chrome's first window (it uses SW_SHOWDEFAULT)
    // — the app window would be created permanently hidden. stdio:"ignore"
    // already keeps the child from borrowing the console.
    let child;
    try {
        child = spawn(browser.exe, args, { stdio: "ignore" });
    } catch (error) {
        ctx.logger.warn(`[app-launcher] failed to launch ${browser.exe}: ${error.message}`);
        return;
    }

    const appExit = ctx.get("appExit");
    const summary = `[app-launcher] ${browser.name} app window opened at ${appUrl} (pid ${child.pid})`
        + (exitOnClose ? "; closing the window shuts down DSH" : "");
    ctx.logger.info(summary);
    // Host logger output is buffered, not printed: mirror the web-app URL line.
    console.log(summary);

    let done = false;
    child.on("exit", () => {
        if (done) return;
        done = true;
        if (!exitOnClose) {
            ctx.logger.info("[app-launcher] app window closed (exitOnClose disabled)");
            return;
        }
        if (typeof appExit === "function") {
            ctx.logger.info("[app-launcher] app window closed; shutting down DSH");
            console.log("[app-launcher] app window closed; shutting down DSH");
            try {
                appExit(0);
            } catch (error) {
                ctx.logger.warn(`[app-launcher] appExit failed: ${error instanceof Error ? error.message : String(error)}`);
            }
        } else {
            ctx.logger.warn("[app-launcher] appExit service unavailable; DSH keeps running");
        }
    });

    // Teardown: close the app window when the tree is disposed (Ctrl+C, update, ...).
    ctx.effect(() => () => {
        done = true;
        try {
            child.kill();
        } catch {
            /* already gone */
        }
    });
}
