// dsh-app-launcher — profile bundle plugin
//
// Turns the DSH Web GUI into a desktop app:
//   1. after the web server is listening (webServer service appears), open the
//      GUI in a dedicated browser app window (own --user-data-dir, so your
//      normal browser profile is never touched);
//   2. when that window is closed, request a graceful process shutdown through
//      the launcher-provided `appExit` service — the npx/cmd wrapper exits on
//      its own, so no external watcher or taskkill is needed;
//   3. optional (Windows): `createShortcut` generates a hidden-start VBS, an
//      .ico, and a Desktop .lnk pointing at them, so a fresh environment gets
//      a one-click launcher automatically.
//
// Config (patch row):
//   enabled:        true   (default)  mount the behavior at all
//   openOnStart:    true   (default)  open the app window on startup
//   exitOnClose:    true   (default)  shut DSH down when the window closes
//   browser:        auto   (default)  'auto' | 'chrome' | 'edge'
//   profileDir:     <dsh-home>/app-window/<browser>   dedicated browser profile
//   createShortcut: true   (default)  create a Desktop launcher shortcut (Windows);
//                                     disable explicitly with false
//   shortcutName:   'DSH'              name of the shortcut (without .lnk)
//   launcherDir:    <dsh-home>/launcher               where VBS/ICO are written
//   desktopDir:     (auto)            target folder for the .lnk (defaults to the real Desktop)

import { spawn } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";
import { ICON_BASE64 } from "./icon.js";

export const name = "app-launcher";

/** Activate only after the web server has bound its socket. */
export const inject = ["webServer"];

const BROWSER_CANDIDATES = {
    win32: [
        { name: "chrome", exe: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe" },
        { name: "chrome", exe: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe" },
        { name: "edge", exe: "C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe" },
        { name: "edge", exe: "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe" }
    ],
    linux: [
        { name: "chrome", exe: "/usr/bin/google-chrome" },
        { name: "chrome", exe: "/usr/bin/google-chrome-stable" },
        { name: "chromium", exe: "/usr/bin/chromium" },
        { name: "edge", exe: "/usr/bin/microsoft-edge" }
    ],
    darwin: [
        { name: "chrome", exe: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome" },
        { name: "edge", exe: "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge" }
    ]
};

function dshHome() {
    return process.env.DSH_HOME || join(homedir(), ".dsh");
}

/** Embed a value in the generated PowerShell script as a single-quoted PS string literal. */
function psQuote(value) {
    return "'" + String(value).replace(/'/g, "''") + "'";
}

/**
 * Create a Desktop shortcut (Windows only): a hidden-start VBS launcher plus
 * an .ico, then a .lnk on the Desktop pointing at wscript.exe + the VBS.
 * Never clobbers existing files: anything already present is left alone.
 * Runs asynchronously via a hidden PowerShell process.
 */
function createDesktopShortcut(ctx, cfg) {
    if (process.platform !== "win32") {
        ctx.logger.info("[app-launcher] createShortcut is Windows-only; skipping");
        return;
    }
    const launcherDir = cfg.launcherDir || join(dshHome(), "launcher");
    const shortcutName = cfg.shortcutName || "DSH";
    const desktopOverride = cfg.desktopDir || "";

    const vbsContent = [
        "' DSH hidden launcher — auto-generated by dsh-app-launcher",
        "' Double-click the Desktop shortcut, or run this file with wscript.",
        "Set shell = CreateObject(\"WScript.Shell\")",
        "shell.Run \"cmd /c npx --yes @deepseek-ai/dsh web\", 0, False"
    ].join("\r\n");

    const script = [
        "$ErrorActionPreference = 'Stop'",
        `$launcherDir = ${psQuote(launcherDir)}`,
        `$shortcutName = ${psQuote(shortcutName)}`,
        `$desktopOverride = ${psQuote(desktopOverride)}`,
        "New-Item -ItemType Directory -Force -Path $launcherDir | Out-Null",
        "$vbsPath = Join-Path $launcherDir 'start-dsh.vbs'",
        "$icoPath = Join-Path $launcherDir 'dsh.ico'",
        "if (-not (Test-Path $vbsPath)) {",
        "  $vbsContent = @'",
        vbsContent,
        "'@",
        "  [System.IO.File]::WriteAllText($vbsPath, $vbsContent, (New-Object System.Text.UTF8Encoding($false)))",
        "}",
        "if (-not (Test-Path $icoPath)) {",
        "  [System.IO.File]::WriteAllBytes($icoPath, [Convert]::FromBase64String('" + ICON_BASE64 + "'))",
        "}",
        "$desktop = if ($desktopOverride) { $desktopOverride } else { [Environment]::GetFolderPath('Desktop') }",
        "if (-not $desktop) { throw 'cannot resolve Desktop path' }",
        "New-Item -ItemType Directory -Force -Path $desktop | Out-Null",
        "$lnk = Join-Path $desktop ($shortcutName + '.lnk')",
        "if (Test-Path $lnk) { Write-Output ('SKIP (exists): ' + $lnk); exit 0 }",
        "$ws = New-Object -ComObject WScript.Shell",
        "$sc = $ws.CreateShortcut($lnk)",
        "$sc.TargetPath = Join-Path $env:windir 'System32\\wscript.exe'",
        "$sc.Arguments = '\"' + $vbsPath + '\"'",
        "$sc.WorkingDirectory = $env:USERPROFILE",
        "$sc.IconLocation = $icoPath + ',0'",
        "$sc.Description = 'Start DeepSeek Harness (DSH) Web GUI'",
        "$sc.Save()",
        "Write-Output ('CREATED: ' + $lnk)"
    ].join("\r\n");

    // The generated script embeds a ~25 KB icon, which would overflow the Windows
    // command line — write it to a temp .ps1 (UTF-8 with BOM so both PowerShell
    // 5.1 and 7 decode non-ASCII paths correctly) and run it with -File.
    let ps1Path;
    try {
        ps1Path = join(tmpdir(), `dsh-create-shortcut-${process.pid}.ps1`);
        writeFileSync(ps1Path, "\uFEFF" + script, "utf8");
    } catch (error) {
        const msg = `[app-launcher] shortcut creation failed to write script: ${error.message}`;
        ctx.logger.warn(msg);
        console.log(msg);
        return;
    }
    let child;
    try {
        child = spawn("powershell.exe", [
            "-NoProfile", "-WindowStyle", "Hidden", "-ExecutionPolicy", "Bypass",
            "-File", ps1Path
        ], {
            stdio: ["ignore", "pipe", "pipe"],
            windowsHide: true
        });
    } catch (error) {
        const msg = `[app-launcher] shortcut creation failed to start: ${error.message}`;
        ctx.logger.warn(msg);
        console.log(msg);
        return;
    }
    let out = "";
    child.stdout.on("data", (d) => { out += String(d); });
    child.stderr.on("data", (d) => { out += String(d); });
    child.on("error", (error) => {
        const msg = `[app-launcher] shortcut creation failed: ${error.message}`;
        ctx.logger.warn(msg);
        console.log(msg);
    });
    child.on("exit", (code) => {
        const msg = `[app-launcher] desktop shortcut: ${out.trim() || `exit ${code}`}`;
        ctx.logger.info(msg);
        console.log(msg);
    });
}

export function apply(ctx, config = {}) {
    const cfg = config || {};
    if (cfg.enabled === false) return;

    const openOnStart = cfg.openOnStart !== false;
    const exitOnClose = cfg.exitOnClose !== false;
    const wantBrowser = cfg.browser && cfg.browser !== "auto" ? cfg.browser : undefined;

    const port = ctx.webServer?.port;
    if (typeof port !== "number") {
        ctx.logger.warn("[app-launcher] webServer.port unavailable; nothing to do");
        return;
    }
    const url = `http://127.0.0.1:${port}`;

    if (cfg.createShortcut !== false) {
        createDesktopShortcut(ctx, cfg);
    }

    if (!openOnStart) {
        ctx.logger.info(`[app-launcher] openOnStart disabled; GUI at ${url}`);
        return;
    }

    const candidates = BROWSER_CANDIDATES[process.platform] ?? [];
    const preferred = wantBrowser ? candidates.filter((c) => c.name === wantBrowser) : [];
    const browser = (preferred.find((c) => existsSync(c.exe)))
        ?? candidates.find((c) => existsSync(c.exe));

    if (!browser) {
        ctx.logger.warn(`[app-launcher] no supported browser found (${candidates.map((c) => c.name).join(", ")}); open ${url} manually`);
        return;
    }

    const profileDir = cfg.profileDir || join(dshHome(), "app-window", browser.name);
    try {
        mkdirSync(profileDir, { recursive: true });
    } catch (error) {
        ctx.logger.warn(`[app-launcher] cannot create profile dir ${profileDir}: ${error.message}`);
        return;
    }

    const args = [
        `--user-data-dir=${profileDir}`,
        `--app=${url}`,
        "--no-first-run",
        "--no-default-browser-check"
    ];

    let child;
    try {
        child = spawn(browser.exe, args, { stdio: "ignore", windowsHide: true });
    } catch (error) {
        ctx.logger.warn(`[app-launcher] failed to launch ${browser.exe}: ${error.message}`);
        return;
    }

    const appExit = ctx.get("appExit");
    const summary = `[app-launcher] ${browser.name} app window opened at ${url} (pid ${child.pid})`
        + (exitOnClose ? "; closing the window shuts down DSH" : "");
    ctx.logger.info(summary);
    // Host logger output is buffered, not printed: mirror the web-app URL line.
    console.log(summary);

    let done = false;
    child.on("exit", () => {
        if (done) return;
        done = true;
        if (!exitOnClose) {
            ctx.logger.info("[app-launcher] app window closed (exitOnClose disabled)");
            return;
        }
        if (typeof appExit === "function") {
            ctx.logger.info("[app-launcher] app window closed; shutting down DSH");
            console.log("[app-launcher] app window closed; shutting down DSH");
            try {
                appExit(0);
            } catch (error) {
                ctx.logger.warn(`[app-launcher] appExit failed: ${error instanceof Error ? error.message : String(error)}`);
            }
        } else {
            ctx.logger.warn("[app-launcher] appExit service unavailable; DSH keeps running");
        }
    });

    // Teardown: close the app window when the tree is disposed (Ctrl+C, update, ...).
    ctx.effect(() => () => {
        done = true;
        try {
            child.kill();
        } catch {
            /* already gone */
        }
    });
}
